### PR TITLE
no type sets

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic please review

**Comment by laughedelic** [comment]
@eparejatobes wow! I didn't expect that you will take it so serious and so soon :flushed::sweat_smile:
But okay, it seems to be fine.. just super-simplifying everything.

**Comment by eparejatobes** [comment]
published this with the branch-scoped version

**Comment by laughedelic** [comment]
:+1: I'm going to try it now

**Comment by laughedelic** [comment]
Seems to compile with minimum of changes (dropping cosas dep).

**Comment by eparejatobes** [comment]
but what?

**Comment by laughedelic** [comment]
no, everything is fine! :ok_hand:

**Comment by eparejatobes** [comment]
@laughedelic I want to stabilize statika and friends by the end of the week. Merging this?

**Comment by laughedelic** [comment]
yep :+1:

**Comment by eparejatobes** [comment]
and what about #9, is your code in all the other repos working with that?

**Comment by laughedelic** [comment]
sorry, missed this. but I guess, that you already fixed it, no?

**Comment by eparejatobes** [comment]
I'm working on it :) Merging this

**Pull request merged**
